<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJd1rpnx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__ . '/ContainerJd1rpnx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJd1rpnx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJd1rpnx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJd1rpnx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jd1rpnx',
    'container.build_id' => '30a36813',
    'container.build_time' => 1582497575,
], __DIR__ . \DIRECTORY_SEPARATOR);
