<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBbrsvx1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBbrsvx1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBbrsvx1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBbrsvx1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBbrsvx1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bbrsvx1',
    'container.build_id' => '44e1744a',
    'container.build_time' => 1582531870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBbrsvx1');
