<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJaSz5r7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJaSz5r7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJaSz5r7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJaSz5r7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJaSz5r7\App_KernelDevDebugContainer([
    'container.build_hash' => 'JaSz5r7',
    'container.build_id' => '6050129d',
    'container.build_time' => 1582530244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJaSz5r7');
